[package]
name = "arrow-urdf-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
arrow = "52.0.0"
arrow-udf = "0.3.0"
async-trait = "0.1.80"
datafusion = "39.0.0"
futures-util = "0.3.30"
anyhow = "1.0.86"
async-stream = "0.3.5"
